### ISSUE TITLE
Issue with yuu

### ISSUE THREAD

**Issue by Strandxo** [Danktuary/vuepress-theme-yuu#13]
VuePress versions tried: "0.14.10", and latest.
Yuu versions tried: "1.0.0", and latest.

For some odd reason, im unable to structure the documentation correctly. The markdown file seems to be covering the whole page starting from the edge of the sidebar which I find odd, is this just a one off error, do you know of a fix and is it common? Ive been trying to find a way to fix this issue for a couple days now.

![image](https://user-images.githubusercontent.com/42255832/65236338-8397b880-db17-11e9-8616-47fefe8df5c9.png)
****

**Comment by Danktuary** [comment]
Hey, sorry for the late reply. I wasn't able to reproduce your issue with Yuu 1.x and VuePress 0.14.x.
But I've now released Yuu 2.x now, which is compatible with VuePress 1.x. Give it a shot and let me know, thanks!

**Comment by jc-aguilera** [comment]
Hijacking this to say version 2.2.0 works perfectly with Vuepress 1.2.0 (crashes with 1.0.2 FWIW)
Thank you very much for this theme :)
![Imgur](https://i.imgur.com/YCcTbhc.png)

**Comment by Strandxo** [comment]
Appreciate the response... For some reason Github didnt notify me when a response was made to my initial post via email or notifications so Ill give it a shot and get back to you. Thank you for responding :)

**Comment by Strandxo** [comment]
Quick Update: I appreciate your response yet again. It seems updating to your newest release has solved this issue, you werent able to replicate it nor is it a problem anymore so Im not able to debug and find the cause. Thank you :)
