### ISSUE TITLE
How to make a custom Home.vue

### ISSUE THREAD

**Issue by Soitora** [Danktuary/vuepress-theme-yuu#17]
I was wondering how to make a custom Home.vue since your theme doesn't seem to supply one?
I've ended up with having all your theme files locally installed then expanding on the default one, I'd prefer if I could just expand on yours instead and only keep 1 overrided file.

**Comment by Danktuary** [comment]
Hey! I suppose you're right, there currently is no way to do so. I did a quick test to see if you could just extend Yuu and only overwrite the `theme/components/Home.vue` file (which is taken from the `@vuepress/theme-default` theme), but it's not as simple as I hoped. Maybe providing another frontmatter option would suffice? i.e.:

```md
<!-- docs/README.md -->
---
home: true
homeComponent: CustomHome
...
---
```

```vue
<!-- docs/.vuepress/components/CustomHome.vue -->
<template>
	<div class="homepage">
		Custom homepage.
	</div>
</template>

<style lang="stylus">
// These variables are available from the default theme
.homepage
	display: block
	max-width: $homePageWidth
	margin: 0 auto
	padding: $navbarHeight 2rem 0
</style>
```

**Comment by Danktuary** [comment]
I added this in v2.3.0 🎉 Thanks for the idea! You can use it as described above.
