### ISSUE TITLE
vuepress next cannot resolve plugin 

### ISSUE THREAD

**Issue by BrianGilbert** [Danktuary/vuepress-theme-yuu#2]
Is it possible to use this with 1.x?

`[vuepress] cannot resolve plugin "/Users/brian/Projects/brian/node_modules/vuepress-theme-yuu"`

**Comment by BrianGilbert** [comment]
On further investigation it appears that this error isn't stopping it from working. Will leave issue open in case it's resolveable though.

**Comment by Danktuary** [comment]
Hey there, sorry for the late reply! I think this is because the theme directory structure for 1.x in comparison to 0.x has been updated a bit. Thankfully not too much, so I'll work this into the 2.x release for Yuu. 😃

**Comment by Danktuary** [comment]
Hey @BrianGilbert, it's been quite a long time but I've finally released 2.x of Yuu. It's now compatible with VuePress 1.x. 🎉
