### ISSUE TITLE
Is it possible to set favicon?

### ISSUE THREAD

**Issue by BrianGilbert** [Danktuary/vuepress-theme-yuu#3]

**Comment by Danktuary** [comment]
I'm not sure if this would be on a theme level or a VuePress level. 😅 If I had to guess, it'd be on a VuePress level, but someone correct me if I'm wrong.

**Comment by BlobCodes** [comment]
@BrianGilbert just create a .vuepress/public folder and throw your favicon(s) in there!
Vuepress will do the rest for you!

[More about that on the docs](https://vuepress.vuejs.org/guide/assets.html#public-files)
