### ISSUE TITLE
Ability to set defaultTheme

### ISSUE THREAD

**Issue by psi-4ward** [Danktuary/vuepress-theme-yuu#4]
Thanks for your theme!
Can we add config options to set the default theme color and dark mode?

**Comment by Danktuary** [comment]
Hey, very sorry about the late reply, but I'll try to work this into 2.x! I'm currently working on it right now, so I'll let you know once it's done and published. 😄

**Comment by Danktuary** [comment]
About 10 months later but better late than never. 😅 `themeConfig.yuu.defaultDarkTheme` and `themeConfig.yuu.defaultColorTheme` are available in vuepress-theme-yuu@^2.2.0!
