### ISSUE TITLE
vuepress build errors

### ISSUE THREAD

**Issue by leaanthony** [Danktuary/vuepress-theme-yuu#5]
Running `vuepress dev` works great with this theme but not `vuepress build`. It seems that it's a [module resolution error](https://github.com/vuejs/vuepress/issues/451) in vuepress. Their suggestion is to use relative paths for importing module. Changing the import path for vue-click-outside in components/settings/UserSettings.vue works for me:

![image](https://user-images.githubusercontent.com/1943904/50721145-85972400-110e-11e9-9516-bbfc33a5519b.png)

**Comment by Danktuary** [comment]
Could you give me some reproduction steps? I ran a fresh install of vuepress and the theme and didn't run into any errors when building.

![](https://i.imgur.com/ngLSqay.png)
![](https://i.imgur.com/1qtCLe4.png)
